[package]
name = "rslsk"
version = "0.1.0"
authors = ["Andrea Bertagnolli <andrea.bertagnolli@cherrychain.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buf_redux = "0.8.4"
md5 = "0.6.1"
hex = "0.4.0"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0"